### ISSUE TITLE
Can't get the access to the paper

### ISSUE THREAD

**Issue by joyce9533** [ck0123/improved-bertscore-for-image-captioning-evaluation#1]
I can't find the paper you mentioned when I searched in google, can you share your thoughts about how you achieve this?

**Comment by ck0123** [comment]
Thanks for your interest! 

Your are so quick that find this repo now. This repo is for the implement of the paper accepted by ACL 2020 (2020-07-05). And because ths deadline of final version of paper is Mar 1st, I do not send the paper to pre-print website and keep revising it.  It will release after Mar 1st at pre-print website on my plan.
