### ISSUE TITLE
About Kendall score

### ISSUE THREAD

**Issue by Yudezhi** [ck0123/improved-bertscore-for-image-captioning-evaluation#2]
In your code, the 'kendall' score is calculated by [scipy.stats.kendalltau()](https://web.archive.org/web/20181008171919/https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.kendalltau.html) ,which is 1945 not 1938. The inter_human(0.736) is cited from "LEIC".
I wonder do you know how the Inter-human score is calculated? I tried many methods but failed to match with 0.736.
By the way, If I keep 2 decimals, the result is matched with Inter-human reported in "SPICE".

Thanks a lot.

**Comment by ck0123** [comment]
Hi Yudezhi,

Thanks for your attention to this paper.
About the experiments, some of them are different among 3 papers ( SPICE, LEIC, ours). It may be caused by different software versions, different implements or different implements. As for inter-human score and LEIC score, we didn't reproduce those, so we just cited them.  It seems that the "inter-human" result 0.73 in SPICE  and 0.736 in LEIC is close. I suggest you can keep using your results in your real environment if you have already reproduced those results.

Best regrads,
yanzhi

**Comment by Yudezhi** [comment]
OK, thanks for your reply.
